#### guide: this script summarize the mapping result of each MAG of three replicates metatranscriptomic sample
#### with -c (capital) in option list, the result of each MAG will be summarized into one file based on row names (transporter/reactions name)
#### the script sometimes can not correctly judge the release compounds (e.g. spermidine, glycine(release))
library(optparse)
library(dplyr)
source('/srv/scratch/z5245780/scripts_and_shell_command/Bacarena/common_function_bacarena_gapseq.R')

option_list = list(
  optparse::make_option(c('-a','--sample_1'),type='character',help = 'the first metatranscriptomic reads batch(e.g. reactions_readscount_X37943_050416_HTSeq_sorted.csv)'),
  optparse::make_option(c('-b','--sample_2'),type='character',help = 'the second metatranscriptomic reads batch'),
  optparse::make_option(c('-c',"--sample_3"),type='character',help = 'the third metatranscriptomic reads batch'),
  optparse::make_option(c("-n","--bin_name"),type='character',help = 'map result belonging to the MAGs'),
  optparse::make_option(c("-d","--directory_list"),type='character',help = 'the summarized multiple directory'),
  optparse::make_option(c("-f","--gtf_reactions"),type='character',help = 'the gtf file generated by HTSeq for normilizing the expression level'),
  optparse::make_option(c("-g","--Transporter_tbl"),type='character',help = 'the transporter.tbl file that is generated by gapseq'),
  optparse::make_option(c("-t","--transporter_db"),default='/srv/scratch/z5245780/software/gapseq/gapseq_1.2/dat/reftrdb_seed.csv',type='character',help = 'transporter database from gapseq(e.g.reftrdb_seed.csv)'),
  optparse::make_option(c("-r","--reaction_db"),default='/srv/scratch/z5245780/software/gapseq/gapseq_1.2/dat/seed_reactions_corrected.tsv',type='character',help = 'reaction database from gapseq (e.g. seed_reactions_corrected.tsv)'),
  optparse::make_option(c("-e","--Reaction_tbl"),type='character',help =  'the reactions.tbl file that is generated by gapseq'),
  optparse::make_option(c("-p","--summrize_reaction"),default=FALSE,type='logical',help='get the average of each reaction across date'),
  optparse::make_option(c("-o","--output"),default='summary.csv',type='character',help='output file (e.g. bin_4_061016_reaction_reads_count.tsv)'),
  optparse::make_option(c("-C", "--collect"), 
              action="store_true", 
              default=FALSE, 
              help=" metatranscriptomic reads count reasults of each bin")
)
opt_parser = optparse::OptionParser(option_list=option_list, add_help_option=FALSE);
opt = optparse::parse_args(opt_parser);


############## function: fixed_lines ####
#' Title
#' Correct the line that includes the compound whose name has a comma by replacing comma with question mark
#' @param sample output file that generated from HTSeq-count (*HTSeq_sorted.csv)
#'
#' @return a dataframe with wrong line fixed
#' @export
#'
#' @examples
fixed_lines<-function(sample){
  
  lines <- readLines(sample)
  fixed_lines <- sapply(lines, function(line) {
    parts <- strsplit(line, ",")[[1]]
    if (length(parts) > 2) {
      # collapse all but the last part
      first_column_ele<-paste(parts[-length(parts)], collapse = ",")
      first_column_modified<-sub(',','?',first_column_ele) ### replace the comma with question mark to avoid being recognized as new column
      
      print(paste0('the line was fixed: ',paste(c(first_column_modified, parts[length(parts)]), collapse = ",")))
      return(paste(c(first_column_modified, parts[length(parts)]), collapse = ","))
    } else {
      return(line)
    }
  })
  transporter_expressed <- read.csv(textConnection(fixed_lines), stringsAsFactors = FALSE, header = FALSE, col.names = c('Name','Reads_count'))
  
  return(transporter_expressed)
}

######## add the reactions id to the dataframe ###
### the reactions id were extracted from transporter_tbl file (e.g. bin_3_merged_2017-Transporter.tbl) ###
### the input form of transporter_count is like this '3.A.1.8.2_molybdate_cpd11574' ###

reaction_id<-function(rowname){
  if (!is.null(opt$Reaction_tbl)){
    ### get the biocyc_id from df merged_final_sorted
    rxn_id<-strsplit(rowname, '_')[[1]][1]
    
    specific_row<-reaction_tbl[reaction_tbl$rxn==rxn_id,][1,]
    
    # If no match found, return NA
    if (nrow(specific_row) == 0) {
      return(NA)
    }
    ### If multiple matches found, retrieve only the first one
    else if (nrow(specific_row) > 1) {
      return(specific_row[1,]$dbhit)
    }
    else{
      return(specific_row$dbhit)
    }
  }
  try({
    tcdb_id <- strsplit(rowname, '_')[[1]][1]
    cpd_name <- sub('\\?',',',strsplit(rowname, '_')[[1]][2]) ### replace the ? to comma to have the compound matching its real name
    
    # If no underscore exists in rowname, this line will raise an error 
    # and the function will return NA
    if (length(c(tcdb_id, cpd_name)) < 2) {
      return(NA)
    }
    
    specific_row <- transporter_tbl[transporter_tbl$tc == tcdb_id & transporter_tbl$sub == cpd_name,]
    
    # If no match found, return NA
    if (nrow(specific_row) == 0) {
      return(NA)
    }
    
    # If multiple matches found, return them concatenated (or handle in another way)
    if (nrow(specific_row) > 1) {
      return(paste(specific_row$rea, collapse = "; "))
    }
    
    return(specific_row$rea)
  }, silent = TRUE)
}

###########################################################################################################################################
################################### check the reactions direction and add the results into the dataframe ###################################
###########################################################################################################################################

####### check if the ex_cpd (e.g. cpd00037[1]) is at the left or right side of the reacting mark '<=>' #####
cpd_position_in_equation<-function(equation,ex_cpd_name){
  
  ### judge if the desired cpd is in the equation or not ### 
  reg_result=regexpr(ex_cpd_name, equation)
  if (length(reg_result)>=1){
    position_cpd <- reg_result[[1]]
  }else{
    return(NULL)
  }
  
  position_symbol <- regexpr("=", equation)[[1]]
  
  # Check the relative positions
  if (position_cpd < position_symbol) {
    return('left')
  } else if (position_cpd > position_symbol) {
    return('right')
  } else {
    print('This scenario should not happen with a well-structured equation')
  }
}

### input one row from df_transporter_count, the function will return transporter direction based on reactions database 'seed_reactions_corrected.tsv' ###
### the input form of transporter_count is like this '3.A.1.8.2_molybdate_cpd11574' ###
#' Title
#'
#' @param line_count one row from merged_final_sorted(dataframe of reads count with reactions_id added)
#'
#' @return direction of each equation in the reactions_id grids
#' @export
#'
#' @examples
#' input 3.A.1.6.1_sodium_cpd00971	0	0	1	0.333333333333333	0.471404520791032	rxn05622,rxn34391,rxn34513
#' output	uptake uptake uptake

check_direction<-function(line_count){
  
  if (is.na(line_count['reactions_id'])|is.null(line_count['reactions_id'])){
    return(NULL)
  }
  rxns_id<-strsplit(line_count['reactions_id'],',')[[1]]
  rxn_equation<-sapply(rxns_id,function(x){reaction_eq_db[which(reaction_eq_db$id==x),]$equation})
  
  cpd_id<-strsplit(line_count['rowname'], '_')[[1]][3]
  ex_cpd_id<-paste0(cpd_id,'\\[1\\]',sep='')
  
  #### judge if the cpd can be uptaken or released or both by checking the compound position in the equation and reacting direction ###
  result<-sapply(rxn_equation,function(equation){
    if(length(equation)==0){
      return(NULL)
    }
    position<-cpd_position_in_equation(equation,ex_cpd_id)
    
    if (grepl('<=>',equation)){
      return('bidirectional')
    }else if(grepl('<=',equation) & position=='left'){
      return('release')
    }else if(grepl('=>',equation) & position=='left'){
      return('uptake')
    }else if(grepl('<=',equation) & position=='right'){
      return('uptake')
    }else if(grepl('=>',equation) & position=='right'){
      return('release')
      #### if the reaction is not included in the database, database seed_reactions will used to do further search ###
    }else{
      print(paste0('please check the compound: ',cpd_id,' and its equation',sep=''))
      return(NULL)
    }
  })
}

###### input the df (e.g. merged_final_sorted) and column name (e.g. sample_1) #####
get_TPM<-function(df,sample){

  RPK<-df[[sample]]* 1000 / df$gene_length
  scalingFactor <- sum(RPK)
  TPM<-RPK/(scalingFactor/1e6)
  
  return(TPM)
}

### summarize the expressed transporters with three replicates ###
if (!is.null(opt$bin_name) && opt$bin_name != ""&&!is.null(opt$sample_1)&&!is.null(opt$Transporter_tbl)){
  
  sample_1=opt$sample_1
  sample_2=opt$sample_2
  sample_3=opt$sample_3
  bin_name=opt$bin_name
  Transporter_tbl=opt$Transporter_tbl
  transporter_db=opt$transporter_db
  reaction_db=opt$reaction_db
  output=opt$output
  
  ############## load the database or reference file ################
  transporter_eq_db<-read.csv(transporter_db,stringsAsFactors = FALSE,sep='\t',quote="")
  reaction_eq_db<-read.csv(reaction_db,stringsAsFactors = FALSE,sep='\t',quote="")
  ### match the TCDB ID to reaction ids using (-Transporter.tbl) ###
  transporter_tbl<-read.table(Transporter_tbl,header=TRUE,stringsAsFactors = FALSE,sep='\t',quote="")
  
  # transporter_expressed_1 <- read.csv(sample_1, stringsAsFactors = FALSE,header=FALSE,col.names = c('Name','Reads_count'))
  # transporter_expressed_2 <- read.csv(sample_2, stringsAsFactors = FALSE,header=FALSE,col.names = c('Name','Reads_count'))
  # transporter_expressed_3 <- read.csv(sample_3, stringsAsFactors = FALSE,header=FALSE,col.names = c('Name','Reads_count'))
  
  transporter_expressed_1<-fixed_lines(sample_1)
  transporter_expressed_2<-fixed_lines(sample_2)
  transporter_expressed_3<-fixed_lines(sample_3)

  ## merge all files above based on transporters/reactions name ###
  merged_df <- merge(transporter_expressed_1, transporter_expressed_2, by = "Name",all=TRUE)
  merged_df2<-merge(merged_df,transporter_expressed_3, by = "Name",all=TRUE)
  
  # adjust the dataframe
  rownames(merged_df2)<-merged_df2[,1]
  merged_df2<-merged_df2[,-1]
  colnames(merged_df2)<-c('sample_1','sample_2','sample_3')
  
  ## Eliminate rows where all values are zero
  merged_final<-merged_df2[apply(merged_df2,1,function(x){any(x!=0)}),]
  
  ### add the average column
  merged_final$average<-apply(merged_final,1,mean)
  merged_final$sd<-apply(merged_final,1,sd)
  
  ### mend the column name to bin name
  merged_final_sorted<-merged_final[order(-merged_final$average),]
  colnames(merged_final_sorted)[colnames(merged_final_sorted) == "average"] <- bin_name
  
  #### add the reactions id into the dataframe ###
  merged_final_sorted$reactions_id<-sapply(rownames(merged_final_sorted),reaction_id)
  
  ### add the direction into the dataframe
  rxn_direction<-apply(merged_final_sorted,1,function(x){paste0(check_direction(x),collapse = '; ')})
  merged_final_sorted$direction<-rxn_direction
  
  #output_file=paste0(bin_name,'_reads_count.csv',seq='')
  write.table(merged_final_sorted,output,sep = "\t", row.names = TRUE,col.names = NA,quote = FALSE) 
  ### col.names = NA: This ensures that the column name of the row names (often an empty name) is not included in the output file.
}

### summarize the expressed reactions with three replicates ###
if(!is.null(opt$Reaction_tbl)){
  expressed_reactions_sample_1=read.csv(opt$sample_1,header=FALSE, col.names = c('name', 'sample_1'),sep=',')
  expressed_reactions_sample_2=read.csv(opt$sample_2,header=FALSE, col.names = c('name', 'sample_2'),sep=',')
  expressed_reactions_sample_3=read.csv(opt$sample_3,header = FALSE, col.names = c('name', 'sample_3'),sep=',')
  bin_name=opt$bin_name
  output=opt$output
  reaction_tbl=read.table(opt$Reaction_tbl,header=TRUE,stringsAsFactors = FALSE,sep='\t',quote="")
  
  # merged_df <- merge(expressed_reactions_sample_1, expressed_reactions_sample_2, 
  #                      by.x = names(expressed_reactions_sample_1)[1], by.y = names(expressed_reactions_sample_2)[1],all = TRUE)
  # merged_df2<- merge(merged_df, expressed_reactions_sample_3, 
  #                   by.x = names(merged_df)[1], by.y = names(expressed_reactions_sample_3)[1],all = TRUE)
  merged_df<-merge(expressed_reactions_sample_1, expressed_reactions_sample_2,by='name',all=TRUE)
  merged_df2<-merge(merged_df, expressed_reactions_sample_3,by='name',all=TRUE)

  rownames(merged_df2)<-merged_df2[,1]
  merged_df2<-merged_df2[,-1];merged_df2[is.na(merged_df2)]<-0
  colnames(merged_df2)<-c('sample_1','sample_2','sample_3')
  
  ## Eliminate rows where all values are zero
  merged_final<-merged_df2[apply(merged_df2,1,function(x){any(x!=0)}),]
  ### add the average column
  merged_final$average<-apply(merged_final,1,mean)
  merged_final$sd<-apply(merged_final,1,sd)
  
  ### mend the column name to bin name
  merged_final_sorted<-merged_final[order(-merged_final$average),]
  colnames(merged_final_sorted)[colnames(merged_final_sorted) == "average"] <- bin_name
  
  ### add rxn seed id based on -all-Reactions.tbl file to a new column
  merged_final_sorted$modelseed_id<-sapply(rownames(merged_final_sorted),reaction_id)
  
  merged_final_sorted$Biocyc_ID <- rownames(merged_final_sorted)
  merged_final_sorted <- merged_final_sorted[, c("Biocyc_ID", colnames(merged_final_sorted)[!colnames(merged_final_sorted) %in% "Biocyc_ID"])]
  
  ######################################################################
  ############## add TPM of each rxn in each sample #########
  gtf<-opt$gtf_reactions
  gtf_file<-read.table(gtf,sep = '\t',header=FALSE,quote = "")
  
  ### To calculate the total length of each reaction, sum the lengths of all associated reaction entries ###
  #rxnid_in_reaction<-merged_final_sorted$Biocyc_ID[5:length(merged_final_sorted$Biocyc_ID)]
  rxnid_in_reaction<-merged_final_sorted$Biocyc_ID[which(!startsWith(merged_final_sorted$Biocyc_ID,'__'))]
  rxnid_in_gtffile<-sapply(gtf_file$V9,function(x){gsub('gene_id ','',strsplit(x,';')[[1]][1],'')}) ### replace the gene id with null in rxn_id
  
  ### get the total gene length and add it to column gene_length in df merged_final_sorted######
  gene_length<-sapply(rxnid_in_reaction,function(x){
    indices<-which(rxnid_in_gtffile==x)
    gene_length<-sum(gtf_file$V5[indices]-gtf_file$V4[indices])
    return(gene_length)
  })
  #merged_final_sorted$gene_length[5:(length(gene_length)+4)]<-gene_length
  merged_final_sorted$gene_length[which(!startsWith(merged_final_sorted$Biocyc_ID,'__'))]<-gene_length
  
  ### remove the row which biocyc_id startwith '__'
  merged_final_sorted<-merged_final_sorted[which(!startsWith(merged_final_sorted$Biocyc_ID,'__')),]
  ### get the TPM of each sample and add to merged_final_sorted ###
  TPM_1<-get_TPM(merged_final_sorted,'sample_1')
  merged_final_sorted$TPM_1<-TPM_1
  
  TPM_2<-get_TPM(merged_final_sorted,'sample_2')
  merged_final_sorted$TPM_2<-TPM_2
  
  TPM_3<-get_TPM(merged_final_sorted,'sample_3')
  merged_final_sorted$TPM_3<-TPM_3
  
  merged_final_sorted$TPM_mean<-apply(merged_final_sorted[,c('TPM_1','TPM_2','TPM_3')],1,mean)
  merged_final_sorted<-merged_final_sorted[order(-merged_final_sorted$TPM_mean),]
  
  write.table(merged_final_sorted,output,sep = "\t", row.names = FALSE,col.names = TRUE,quote = FALSE) 
  
}

### this option read all files with suffix '_reads_count.csv', and merge them into one summarized file ##
if (opt$collect) {
  file_list <- list.files(pattern = "_reads_count\\.tsv$")
  df_list <- lapply(file_list, function(file) {
    df<-read.table(file, stringsAsFactors = FALSE,quote="",sep='\t',header = TRUE)
    ## take the first column as row names

    df_average <- df[, -c(2:4,6)]
    df_average$rowname <- df[,1]
    return(df_average)}) ### the list that contains all the dataframes of average reads count
  ### merge the df in df_list one by one
  merged_df <- Reduce(function(x, y) {merge(x, y, by = c("rowname","reactions_id","direction"), all = TRUE)}, df_list)
  merged_df<-merged_df[,grep('^bin_|^rowname|reactions_id|direction',colnames(merged_df))]
  
  ######## remove the TCDB id in column name ########
  new_rowname<-sapply(merged_df$rowname,function(x) sub("^[^_]*_", "",x))
  merged_df$rowname<-new_rowname
  
  ####### sum the reads count based on the rowname, reactions_id and direction (group_by(rowname,reactions_id,direction))###
  ### the rowname need to be switched to lowercase to merge as many as possible rows using command (mutate(rowname = tolower(rowname))) ####
  df_t<-merged_df %>% mutate(rowname = tolower(rowname)) %>% group_by(rowname,reactions_id,direction) %>% summarise(across(everything(), sum, na.rm = TRUE))
  
  df_t <- df_t %>% mutate(across(everything(), ~ ifelse(. == 0, NA, .)))
  
  write.table(df_t,'summary.tsv',quote = FALSE,row.names=FALSE,sep='\t')
}

######### generate the reaction summary of each bin across the collected date #########
if (opt$summrize_reaction){
  directory_list<-strsplit(opt$directory_list,',')[[1]]
  bin_name<-opt$bin_name
  #### input directory list and bin_name then return a list containing all the dataframe of count reads with column(X,reactions_id,direction,collected_date)
  ######### get the reads count of the bin across the collected dat ##########
  # df_list<-lapply(directory_list,function(x){file<-read.table(paste0(x,'/',bin_name,'_',x,'_reads_count.tsv'),sep='\t',quote="",header=TRUE)
  # file<-file[,c('Biocyc_ID',bin_name,'modelseed_id')]
  # colnames(file)[2]<-strsplit(x,'_')[[1]][1]
  # return(file)})
  ######### get the TPM of the bin across the collected dat ##########
  df_list<-lapply(directory_list,function(x){file<-read.table(paste0(x,'/',bin_name,'_',x,'_reads_count.tsv'),sep='\t',quote="",header=TRUE,fill=TRUE)
  if (all(c('Biocyc_ID','TPM_mean','modelseed_id') %in% colnames(file))){
    file<-file[,c('Biocyc_ID','TPM_mean','modelseed_id')]
    colnames(file)[2]<-strsplit(x,'_')[[1]][1]
    return(file)
  }else{
    columns_to_add <- c('Biocyc_ID', 'TPM_mean', 'modelseed_id')
    
    # Iterate over the list of columns and add them if they don't exist
    for (col in columns_to_add) {
      if (!(col %in% colnames(file))) {
        # If the column does not exist, add it with default values
        # Here I'm adding NA values, but you can replace NA with any default value you prefer
        file[[col]] <- NA
      }
    }
    return(file)
  }})

  merged_df_bin <- Reduce(function(x, y) {
    merge(x, y, by = c('Biocyc_ID','modelseed_id'), all = TRUE)
  }, df_list)
  
  # ### extract the character(s) before the first underscore (biocyc rxn id)
  # merged_df_bin$Biocyc_ID_modified<-sub('_(.*)','',merged_df_bin$Biocyc_ID)
  # merged_df_bin <- merged_df_bin[, -which(names(merged_df_bin) == "Biocyc_ID")]

  df_t_bin<-merged_df_bin %>% group_by(Biocyc_ID,modelseed_id) %>% summarise(across(everything(), sum, na.rm = TRUE))
  df_t_bin <- df_t_bin %>% mutate(across(everything(), ~ ifelse(. == 0, NA, .)))
  
  ### replace the NA with 0 and sort the entire df based on the generated average column
  
  df_t_bin[,3:9] <- apply(df_t_bin[,3:9], 2, function(col) ifelse(is.na(col), 0, col))
  df_t_bin$TPM_mean<-rowMeans(df_t_bin[1:nrow(df_t_bin),3:9],na.rm=TRUE)
  
  ### check the subunits : added on 24112024 ##
  rxn_all<-read.csv(paste('/srv/scratch/z5245780/Cymbastela_concentrica/sanger_sequencing/CC_sanger_final_bins/',mag_name,'/draft/',mag_name,'-all-Reactions.tbl',sep=''),quote="",header=TRUE,sep='\t',comment.char = '#')
  index_vector<-c()
  for (i in seq_along(df_t_bin$Biocyc_ID)){
    biocyc_info<-str_split(df_t_bin$Biocyc_ID[i],'_')[[1]]
    
    if (biocyc_info[2]=='good'){ ## only consider those good_blast reactions
      if (biocyc_info[4]=='NA'){# if the enzyme is not multiple subunit
        index_vector<-c(index_vector,i)
      }else{ # if the enzyme has multiple subunits
        biocyc_id<-biocyc_info[1]
        rxn_index<-which(grepl(biocyc_id,rxn_all$rxn))
        
        if (length(rxn_index) > 0) {
          result <- check_subunit(rxn_index, rxn_all)
          if (!is.na(result) && result == "reaction found") {
            index_vector <- c(index_vector, i)
          }
        }
      }
    }
  }
  df_t_bin<-df_t_bin[index_vector,]
  
  ## reorder based on average TPM
  df_t_bin_sorted <- df_t_bin[order(-df_t_bin$TPM_mean), ]
  
  write.table(df_t_bin_sorted,paste0('summary_TPM',bin_name,'.tsv'),quote = FALSE,row.names=FALSE,sep='\t')
}

######### generate the transporter summary of each bin across the collected date #########
if (!is.null(opt$directory_list)&&opt$summrize_reaction==FALSE){
  directory_list<-strsplit(opt$directory_list,',')[[1]]
  bin_name<-opt$bin_name
  #### input directory list and bin_name then return a list containing all the dataframe of count reads with column(X,reactions_id,direction,collected_date)
  df_list<-lapply(directory_list,function(x){file<-read.table(paste0(x,'/',bin_name,'_',x,'_reads_count.tsv'),sep='\t',quote="",header=TRUE)
  file<-file[,c('X', 'reactions_id', 'direction',bin_name)]
  colnames(file)[4]<-strsplit(x,'_')[[1]][1]
  return(file)})
  
  merged_df_bin <- Reduce(function(x, y) {
    merge(x, y, by = c('Biocyc_ID','modelseed_id'), all = TRUE)
  }, df_list)
  
  ### retrieve the character(s) before the first underscore
  merged_df_bin$Biocyc_ID_modified[1:4]<-merged_df_bin$Biocyc_ID[1:4]
  merged_df_bin$Biocyc_ID_modified[4:nrow(merged_df_bin)]<-sub('_(.*)','',merged_df_bin$Biocyc_ID[4:nrow(merged_df_bin)])
  merged_df_bin <- merged_df_bin[, -which(names(merged_df_bin) == "Biocyc_ID")]
  
  df_t_bin<-merged_df_bin %>% group_by(Biocyc_ID_modified,modelseed_id) %>% summarise(across(everything(), sum, na.rm = TRUE))
  df_t_bin <- df_t_bin %>% mutate(across(everything(), ~ ifelse(. == 0, NA, .)))
  
  ### replace the NA with 0 and sort the entire df based on the generated average column
  df_t_bin[,3:9] <- apply(df_t_bin[,3:9], 2, function(col) ifelse(is.na(col), 0, col))
  df_t_bin$average<-rowMeans(df_t_bin[1:nrow(df_t_bin),3:9],na.rm=TRUE)
  df_t_bin_sorted <- df_t_bin[order(-df_t_bin$average), ]  
  
  write.table(df_t_bin_sorted,paste0('summary_',bin_name,'.tsv'),quote = FALSE,row.names=FALSE,sep='\t')
}

# # ## refined the summary by checking the subunits and removing bad blast entries
# # Get all filenames in the current directory
# files <- list.files()
# 
# # Extract the text between 'summary_TPM' and '.tsv'
# extracted <- gsub(".*summary_TPM(.*?)\\.tsv.*", "\\1", files)
# for (mag_name in extracted){
#   summary_df<-read.csv(paste('summary_TPM',mag_name,'.tsv',sep=''),quote="",header=TRUE,sep='\t')
#   rxn_all<-read.csv(paste('/srv/scratch/z5245780/Cymbastela_concentrica/sanger_sequencing/CC_sanger_final_bins/',mag_name,'/draft/',mag_name,'-all-Reactions.tbl',sep=''),quote="",header=TRUE,sep='\t',comment.char = '#')
#   
#   index_vector<-c()
#   for (i in seq_along(summary_df$Biocyc_ID)){
#     biocyc_info<-str_split(summary_df$Biocyc_ID[i],'_')[[1]]
#     
#     if (biocyc_info[2]=='good'){ ## only consider those good_blast reactions
#       if (biocyc_info[4]=='NA'){# if the enzyme is not multiple subunit
#         index_vector<-c(index_vector,i)
#       }else{ # if the enzyme has multiple subunits
#         biocyc_id<-biocyc_info[1]
#         rxn_index<-which(grepl(biocyc_id,rxn_all$rxn))
#         
#         if (length(rxn_index) > 0) {
#           result <- check_subunit(rxn_index, rxn_all)
#           if (!is.na(result) && result == "reaction found") {
#             index_vector <- c(index_vector, i)
#           }
#         }
#       }
#     }
#   }
#   new_df<-summary_df[index_vector,]
#   write.table(new_df,paste('summary_TPM',mag_name,'_refined.tsv',sep=''),quote=FALSE,row.names=FALSE,sep='\t')
# }
